import gradio as gr

theme = gr.themes.Base(
    primary_hue=gr.themes.Color(c100="#b1ded6", c200="#7fc9bc", c300="#4db4a2", c400="#26a38e", c50="#dff2ef", c500="#01937c", c600="#008670", c700="#007660", c800="#006652", c900="#004a37", c950="#134034"),
    secondary_hue=gr.themes.Color(c100="#b1ded6", c200="#7fc9bc", c300="#4db4a2", c400="#26a38e", c50="#dff2ef", c500="#01937c", c600="#008670", c700="#007660", c800="#006652", c900="#134e4a", c950="#12443e"),
    neutral_hue=gr.themes.Color(c100="#f6f5f4", c200="#e5e5e5", c300="#d4d4d4", c400="#a3a3a3", c50="#dff2ef", c500="#737373", c600="#525252", c700="#007660", c800="#262626", c900="#004a37", c950="#0f0f0f"),
    text_size="lg",
    radius_size="sm",
    font=[gr.themes.GoogleFont('Arial'), 'ui-sans-serif', 'system-ui', 'sans-serif'],
    font_mono=[gr.themes.GoogleFont('ubuntu'), 'IBM Plex Mono', 'Consolas', 'monospace'],
).set(
    body_text_color='*neutral_950',
    body_text_color_subdued='*neutral_950',
    embed_radius='*radius_xl',
    border_color_accent='*secondary_600',
    border_color_primary='*secondary_600',
    color_accent='*secondary_500',
    color_accent_soft='*primary_200',
    shadow_drop='*button_shadow_hover',
    shadow_drop_lg='*button_shadow_hover',
    shadow_spread='*shadow_drop_lg',
    shadow_spread_dark='*shadow_inset',
    block_background_fill='*background_fill_secondary',
    block_background_fill_dark='*neutral_950',
    block_border_color='*secondary_700',
    block_label_background_fill='*background_fill_secondary',
    block_label_border_width='*checkbox_label_border_width',
    block_label_shadow='*checkbox_shadow',
    block_label_text_color='*secondary_950',
    block_label_text_color_dark='secondary_50',
    block_label_margin='1',
    block_padding='*spacing_xs',
    block_title_background_fill='*primary_50',
    block_title_background_fill_dark='*neutral_950',
    block_title_border_color='*button_primary_border_color',
    panel_background_fill='*secondary_100',
    chatbot_code_background_color='*secondary_50',
    checkbox_background_color='*neutral_50',
    checkbox_border_color='*neutral_950',
    checkbox_border_color_focus='*secondary_950',
    checkbox_border_color_hover='*neutral_700',
    checkbox_border_color_hover_dark='*neutral_700',
    checkbox_border_radius='*radius_md',
    input_background_fill_focus='*secondary_600',
    table_border_color='*neutral_950',
    table_border_color_dark='*neutral_300',
    table_odd_background_fill='*secondary_300',
    table_odd_background_fill_dark='*secondary_600',
    button_shadow='*shadow_drop_lg',
    button_shadow_active='*shadow_drop_lg',
    button_primary_background_fill_hover='*button_secondary_background_fill',
    button_primary_background_fill_hover_dark='*button_secondary_background_fill',
    button_secondary_text_color="*secondary_50",
    button_secondary_text_color_dark="*secondary_50",
    button_secondary_background_fill='*secondary_600',
    button_secondary_background_fill_dark='*secondary_800',
    button_secondary_border_color='*secondary_950',
    button_secondary_border_color_dark='*secondary_50',
    block_title_text_color='*secondary_950',
    block_title_text_color_dark='*secondary_50',
    input_placeholder_color='*secondary_950',
    input_placeholder_color_dark='*secondary_50',
    link_text_color= '*secondary_950',

)
